apiVersion: v1
kind: Service
metadata:
  name: planner-api
  namespace: brightroom
spec:
  type: ClusterIP
  selector:
    app: planner-api
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
